-- Who logs in, how, and from what client -- needed to judge whether "weak auth"
-- detection has anything to key off (MFA factor, client type, etc).

SELECT
    USER_NAME,
    COUNT(*) AS login_attempts
FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
GROUP BY USER_NAME
ORDER BY login_attempts DESC;

SELECT
    FIRST_AUTHENTICATION_FACTOR,
    SECOND_AUTHENTICATION_FACTOR,
    COUNT(*) AS attempts
FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
GROUP BY FIRST_AUTHENTICATION_FACTOR, SECOND_AUTHENTICATION_FACTOR
ORDER BY attempts DESC;

SELECT
    REPORTED_CLIENT_TYPE,
    REPORTED_CLIENT_VERSION,
    COUNT(*) AS attempts
FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
GROUP BY REPORTED_CLIENT_TYPE, REPORTED_CLIENT_VERSION
ORDER BY attempts DESC;
