-- SECOND_AUTHENTICATION_FACTOR is always null in this data -- check whether
-- LOGIN_DETAILS / CONNECTION / AUTHORIZING_INTEGRATION_NAME carry any MFA or
-- key-pair auth signal that would still support a "weak auth" detection.

SELECT
    EVENT_TIMESTAMP,
    USER_NAME,
    FIRST_AUTHENTICATION_FACTOR,
    CONNECTION,
    AUTHORIZING_INTEGRATION_NAME,
    LOGIN_DETAILS
FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
ORDER BY EVENT_TIMESTAMP DESC;
